-- Active: 1788435085055@@127.0.0.1@3306@smartcoffee_dml_rafael
-- DQL - DATA QUERY LANGUAGE (LINGUAGEM DE CONSULTA DE DADOS)
-- ANTES DE INICIAR
USE SMARTCOFFEE_DML_RAFAEL;
INSERT INTO cliente (nome, email, telefone, cidade, ativo) VALUES
('Ana Flávia', 'anaf@email.com', '199984512456', 'Campinas', TRUE);

-- EX 1: SELECT SIMPLES OU CONSULTA SIMPLES
-- ESTRUTURA SELECT POR EXEMPLO
-- SELECT coluna
-- FROM tabela;
SELECT *
FROM cliente;
-- CONSULTAR TODAS AS COLUNAS

SELECT nome, telefone
FROM cliente;
-- CONSULTAR COLUNAS ESPECIFICAS

-- EX 2: ALIAS COM AS COMO APELIDO OU NOVO NOME AS COLUNAS
SELECT nome AS NOME_CLIENTE
FROM cliente;

SELECT email AS EMAIL_CLIENTE, telefone AS CONTATO_CLIENTE;

-- EX 3: DISTINT - ELIMINADO REPETIÇÕES
SELECT DISTINCT cidade
FROM cliente;
-- SEM DISTINT O RESULTADO IRA SE REPETIR MAIS VEZES
-- COM DISTINT O RESULTADO IRA APARECER UMA VEZ

-- EX 4: WHERE - FILTRO POR REGISTROS
-- IREMOS DEFINIR CONDIÇÕES
-- = IGUAL
-- <> OU != DIFERENTE
-- > MAIOR QUE
-- >= MAIOR OU IGUAL
-- < MENOR QUE
-- <= MENOR OU IGUAL
SELECT nome, preco
FROM produto
WHERE preco > 10.00;
-- CONSULTA PARA VALORES ACIMA DE 10.00 REAIS

SELECT nome, preco
FROM produto
WHERE ativo = TRUE;
-- CONSULTA STATUS DE CLIENTE SE ESTA ATIVO OU INATIVO

SELECT id_pedido, data_pedido, valor_total
FROM pedido
WHERE valor_total >= 25.00;
-- COSULTA PEDIDOS ACIMA DE DETERMINADO VALOR

-- EX 5: USO DO AND, OR E NOT
-- AND TODAS AS CONDIÇÕES VERDADEIRAS
SELECT nome, preco
FROM produto
WHERE preco >= 8.00 AND preco <= 25.00;

-- OR PELO MENOS UMA CONDIÇÃO VERDADEIRA
SELECT nome, cidade
FROM cliente
WHERE cidade = 'Limeira' OR cidade = 'Piracicaba';

-- NOT NÃO IRA BUSCAR OU CONSULTAR O VALOR DESEJADO
SELECT nome, cidade
FROM cliente
WHERE NOT cidade = 'Limeira';

-- EXTRA - UTILIZANDO AND E OR JUNTOS SEPARAR POR ()
SELECT nome, cidade, ativo
FROM cliente
WHERE ativo = TRUE
AND (cidade = 'Limeira' OR cidade = 'Piracicaba');

-- EX 6: BETWEEN - ENTRE DOIS VALORES
-- LIMITE INICIAL E FINAL
SELECT nome, preco
FROM produto
WHERE preco BETWEEN 8.00 AND 15.00;
-- CONSULTA POR VALORES ENTRE 8 E 15

SELECT id_pedido, data_pedido, valor_total
FROM pedido
WHERE data_pedido BETWEEN '2026-09-01 00:00:00' AND '2026-09-30';
-- CONSULTA POR INTERVALO DE DATAS

-- EX 7: IN VARIAS POSSIBILIDADES 
SELECT nome, cidade
FROM cliente
WHERE cidade IN ('Limeira','Campinas','Americana','Piracicaba');
-- CONSULTA COM VARIAS CONDIÇÕES E DIMINUINDO O USO DE OR

SELECT nome, cidade
FROM cliente
WHERE cidade NOT IN ('Limeira','Piracicaba');
-- CONSULTA COM EXCESSÃO DOS VALORES ESPECIFICADOS

-- EX 8: LIKE - PESQUISA POR TEXTOS
-- CORINGAS
-- % VARIOS CARACTERES
-- _ EXATAMENTE UM CARACTER
SELECT nome
FROM produto
WHERE nome LIKE 'Cafe%';
-- CONSULTA TODOS OS PRODUTOS QUE COMEÇAM COM A PALAVRA DESEJADA

SELECT nome
FROM produto
WHERE nome LIKE '%chocolate';
-- CONSULTA TODOS OS PRODUTOS QUE POSSUAM A PALAVRA DESEJADA

SELECT nome
FROM cliente
WHERE nome LIKE '%Silva';
-- CONSULTA TODOS OS CLIENTES QUE TERMINAM COM A PALAVRA DESEJADA

SELECT nome
FROM cliente
WHERE nome LIKE '%Si_va';
-- CONSULTA ESPECIFICAMENTE O CARACTER QUE NÃO SE LEMBRA

-- EX 9: NULL - AUSÊNCIA DE VALORES 
SELECT nome, telefone
FROM cliente
WHERE telefone IS NULL;
-- CONSULTA CAMPOS QUE POSSUEM O NULL

SELECT nome, telefone
FROM cliente
WHERE telefone IS NOT NULL;
-- CONSULTA CAMPOS QUE NÃO SÃO MAIS NULL

-- EX 10: ORDER BY - ORDENANDO RESULTADOS
-- ASC CRESCENTE
-- DESC DECRESCENTE
SELECT nome, preco
FROM produto
ORDER BY preco ASC;
-- CONSULTAR DADOS DE FORMA CRESCENTE

SELECT nome, preco
FROM produto
ORDEM BY preco DESC;
-- CONSULTAR DADOS DE FORMA DECRESCENTE

SELECT cidade, nome
FROM cliente
ORDER BY cidade ASC, nome DESC;
-- CONSULTA POR MAIS DE UMA COLUNA

-- EX 11: LIMIT - LIMITAR QUANTIDADE DE LINHAS
SELECT nome, preco
FROM produto
ORDER BY preco DESC
LIMIT 10;
-- CONSULTAR APENAS UMA QUANTIDADE ESPECIFICA DE LINHAS

SELECT nome, preco
FROM produto
ORDER BY nome
LIMIT 5 OFFSET 5;
-- CONSULTAR COM LIMITE DE VALORES E LINHAS

-- EX 12: CALCULO DE COLUNAS
SELECT nome, preco, preco * 2 AS preco_ajustado
FROM produto;

SELECT id_item, quantidade, preco_unitario, quantidade * preco_unitario AS SUB_TOTAL
FROM item_pedido;

-- EX 13: FUNÇÕES PARA CONSULTAS
-- TEXTOS
SELECT UPPER(nome) AS NOME_CLIENTE, LOWER(email) AS EMAIL_CLIENTE
FROM cliente;

SELECT CONCAT(nome, ' --- ', cidade) AS CIDADE_CLIENTES
FROM cliente;
-- CONCAT: concatenação de valores

-- NUMEROS
SELECT nome, preco, ROUND(preco * 0.90, 2) AS PRECO_DESCONTO
FROM produto;

-- DATAS
SELECT id_pedido, data_pedido, DATE(data_pedido) AS DATAS, MONTH(data_pedido) AS Mês, YEAR(data_pedido) AS Ano, DAY(data_pedido) AS Dia, TIME(data_pedido) AS Horário
FROM pedido;

-- COALENCE - SUBSTITUIR A INFORMAÇÃO QUE DEIXAMOS EM NULL OU NÃO DEIXAMOS
SELECT nome, COALESCE(telefone, 'Não Informado') AS telefone
FROM cliente;